# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUKChgxtwK_ZmmC-s5QNu5lOp4GwqCXt
"""

import requests
import json

# ScaleDown API endpoint
url = "https://api.scaledown.xyz/compress/raw/"
with open("text_content.json", "r") as f:
    loaded_content = json.load(f)

# Your headers (replace YOUR_API_KEY with your actual key)
headers = {
    'x-api-key': 'SCALEDOWN_API_KEY',
    'Content-Type': 'application/json'
}
payload = {
    "context": loaded_content["content"][0]["text"],
    "prompt": "what is the experience and qualifications of the indivisual",
    "scaledown": {
        "rate": "auto" # Automatic compression rate optimization
    }
}
response = requests.post(url, headers=headers, data=json.dumps(payload))
result = response.json()

print(result)

from google import genai
from pydantic import BaseModel

# Initialize the modern client
client = genai.Client(api_key="YOUR_GEMINI_API_KEY")

# Define a Schema for the response to ensure 100% reliability
class MatchResult(BaseModel):
    match_percentage: int
    justification: str
    missing_skills: list[str]

def calculate_resume_match(resume_text, job_description):
    prompt = f"""
    Analyze the following Resume against the Job Description.
    Calculate a match percentage (0-100) and identify missing requirements.

    JD: {job_description}
    Resume: {resume_text}
    """

    # The new SDK handles structured outputs natively
    response = client.models.generate_content(
        model="gemini-2.0-flash", # Or gemini-3-flash-preview
        contents=prompt,
        config={
            "response_mime_type": "application/json",
            "response_schema": MatchResult,
        }
    )

    # The result is already a typed object/dict thanks to response_schema
    return response.parsed

# Example Usage
resume = result['results']['compressed_prompt']
jd = "We need a Senior Data Scientist with 6+ years in Python and SQL. "# Change as required

result = calculate_resume_match(resume, jd)

print(f"Match: {result.match_percentage}%")
print(f"Gap Analysis: {result.missing_skills}")